### ISSUE TITLE
Caption Sizes

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/video50#104]
Via @dmalan and @dlloyd09:

Caption sizes in the PiP window should scale with the window size, as the captions do for the main window but should have a min-height (just make it look proportional as shown in the main window).

**Comment by lukejacksonn** [comment]
Fixed in https://github.com/cs50/video50/pull/119 this is not as trivial as it sounds as `element-queries` do not yet exist and you can not relate font-size to a parent element's size that is not the window (when the parent is the window, as with the main-video captions, you can simply use `vw` and `vmin` units).
