### ISSUE TITLE
In multi-screen mode, when you click "play", PiP window becomes full-screen but should play inline

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/video50#110]
via @dmalan and @dlloyd09

**Comment by lukejacksonn** [comment]
I presume this is describing behavior in a mobile context.. I added the `playsinline: 1` attribute to the `playerVars` object and now the videos load inline but as far as I can tell YouTube have a mechanism of ensuring only one player is playing at any one time.

That is.. if you have more than one videos on screen, both with `playsinline: 1` set, when you hit play on one, the others will pause. Same happens if you call `player.playVideo()` programatically.

Here is a demo as simple, as it gets:
https://codepen.io/lukejacksonn/pen/wdGNxX

Perhaps it was a little ambitious to hope for such a demanding feature to work on mobile. Probably the safest thing to do here is only render the multiscreen and explained mode buttons when `isMobile() === false`.

**Comment by dmalan** [comment]
Hm, this does seem to work now (on Chrome on iOS), whereby tapping the PiP played does toggle the sources without full-screening. Are you still finding otherwise?

**Comment by lukejacksonn** [comment]
The videos display on screen at the same time and they switch places fine too. They just can't both be playing at the same time.. or at least they aren't for me. Are both playing for you?

**Comment by lukejacksonn** [comment]
@dmalan are the two videos in fact playing simultaneously for you? I have tested on my device (iPhone 5) and also an iPhone 6 to no avail. If this is in fact true then..

> Probably the safest thing to do here is only render the multiscreen and explained mode buttons when isMobile() === false.

**Comment by dmalan** [comment]
Yup, works in both Chrome and Safari on latest iOS on an iPhone 7!

![img_0479](https://cloud.githubusercontent.com/assets/788678/25407612/f71d1586-29d8-11e7-8d46-5ea59ef0cb23.PNG)
![img_0478](https://cloud.githubusercontent.com/assets/788678/25407613/f71d59c4-29d8-11e7-98e7-eab7a47d6d1d.PNG)

**Comment by lukejacksonn** [comment]
I observed that they are loading/seeking together, which gives the illusion that all is working but if you sit and watch for a slide change it becomes apparent (on my devices at least) that they are not both playing simultaneously. Perhaps it is an iPhone < 7 thing but that would be strange.

**Comment by dmalan** [comment]
Okay, let's disable Explained mode in mobile in that case.

**Comment by lukejacksonn** [comment]
Implemented here https://github.com/cs50/video50/pull/122
