### ISSUE TITLE
Increase size of small fonts for visually impaired users

### ISSUE THREAD

**Issue by chrisauclair** [cs50/video50#85]
In a few places, the fonts are too small for visually impaired users. For example, in the chapters panel, the `font-size` for the length of each chapter is `0.7em`. In general, fonts should be no smaller than `0.875em` (`14px`), but if possible the preferred font size for text is be at least `1em` (`16px`).

**Comment by lukejacksonn** [comment]
I did a quick check whilst implementing https://github.com/cs50/video50/pull/123 for font-size scaling (when a user hits `cmd +/-`) and although at default scaling some font-sizes get rendered at `< 14px` nearly all text is sized using `rem` units and thus scale with the body font-size (still usable up to `200%` scaling).

Due to this, I am going to mark the issue as closed. Feel free to reopen/discuss further if needs be!

**Comment by chrisauclair** [comment]
Default font sizes should generally stay above 14 px (or the equivalent computed value) and ideally be above 16 px. However, kudos for implementing scaling fonts.
