### ISSUE TITLE
Pressing tab key should toggle player controls to visible

### ISSUE THREAD

**Issue by chrisauclair** [cs50/video50#86]
To support keyboard users, pressing `tab` or `shift + tab` should also trigger the visible state of the controls, just like moving the mouse does for mouse users. Keep in mind that keyboard users should not lose their previous position when the controls toggle back to visible.

**Comment by lukejacksonn** [comment]
Hey @chrisauclair! I'm not sure when you last tested this, but since the issue was opened there has been a refactor. When I test it now (on chrome at least) the controls are becoming active as if the mouse had been moved, as well the last focus element seems to be remembered, when the `tab` or `shift + tab` keys are pressed!

Can you confirm this behavior and perhaps suggest if it is sufficient enough for this issues to be closed?

**Comment by lukejacksonn** [comment]
This has been addressed and tested in https://github.com/cs50/video50/pull/123

**Comment by chrisauclair** [comment]
Great to see that this works now when using `tab` and `shift + tab`, and that focus remains. There is one oversight on my part: when arrow keys are used to navigate through the video, controls should become visible.
